### ISSUE TITLE
settings for small ball 

### ISSUE THREAD

**Issue by gitunit** [rozumden/fmo-cpp-demo#5]
what radius and dfactor would you recommend for videos with following views:

![image](https://user-images.githubusercontent.com/6443378/94012215-c5051880-fda8-11ea-8988-0254fc71d05e.png)

so far it couldn't detect anything yet

**Comment by gitunit** [comment]
changing to median-v2 shows some results, while the default "taxonomy-v1" is not detecting the ball at all (debug shows it's focusing rather on players and the court). any suggestions how to stabilize it more? i was playing a bit with the dfactor param, that shows some changes in the results. changing p2cm/radius affects only the calculation of the speed, is that right?

**Comment by gitunit** [comment]
also what makes this a bit more challenging is the moving camera. what do you think, would stabilizing the video help?

**Comment by rozumden** [comment]
Changing p2cm/radius indeed affects only the calculation of speed. The parameter dfactor changes how sensitive is the method with respect to noise and low contrast. 

If your sequence is not stable due to shaking or moving camera, you could try to stabilize it with OpenCV or just using some online tool - https://video-stabilize.com/
Stabilized video would definitely make the detection more robust and would definitely help.
